[package]

name = "ifaces"
version = "0.0.2"
authors = [
    "David Levy <dlevy47>",
    "Steve Klabnik <steve@steveklabnik.com>",
    "misuzu <bakalolka@gmail.com>"
]
license = "MIT"

[dependencies]
nix = "0.5.0"
libc = "0.2.8"

[[bin]]
path = "src/bin/ifaces.rs"
name = "ifaces"
